version: '3'
services:

    ubuntu_1:
        image: ubuntu:latest
        tty: true
        stdin_open: true
    
    ubuntu_2:
        image: ubuntu:latest
        tty: true
        stdin_open: true

    grafana:
        image: grafana/grafana:latest
        ports:
            - '3000:3000'
    
    

